# Generated by Django 5.2.8 on 2025-11-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationotp',
            name='last_sent_at',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='last_sent_at',
        ),
    ]
