# Generated by Django 5.2.8 on 2025-12-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiumchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='case',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
