# Generated by Django 5.2.8 on 2025-12-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_remove_case_medical_visit'),
        ('premiumchat', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='case.case')),
            ],
        ),
        migrations.DeleteModel(
            name='PremiumChatMessage',
        ),
    ]
