# Generated by Django 5.2.8 on 2025-12-01 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room_name',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
