# Generated by Django 5.2.8 on 2025-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='medical_visit',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
