# Generated by Django 5.2.8 on 2025-12-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_case_medical_visit_alter_case_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='medical_visit',
        ),
    ]
